/**
 * PatchProof AI domain types.
 *
 * PRIMARY data (entered by the user, stored in Firebase):
 *   - Website        : the client site being monitored
 *   - ChangeEvent    : a detected/reported change on that site
 *
 * DERIVED data (generated by the deterministic engine, stored in Firebase):
 *   - Issue          : analysis of a change (impact, dependencies, repair, safety)
 *   - Journey        : protected business journey derived from a website's business functions
 *   - EvidenceRecord : proof-of-repair produced when a workflow completes
 */

export type WebsiteStatus = "Healthy" | "Attention Required" | "Critical";

export type IssueStatus =
  | "Detected"
  | "Analysed"
  | "Repair Proposed"
  | "Awaiting Approval"
  | "Approved"
  | "Validation Required"
  | "Resolved"
  | "Rejected";

export type Risk = "Low" | "Medium" | "High" | "Critical";
export type JourneyStatus = "Healthy" | "At Risk" | "Validation Required" | "Passed" | "Failed" | "Not Present";
export type EvidenceStatus = "Verified" | "Pending";

/** PRIMARY — exactly what the user provides about a website. */
export type WebsiteRecord = {
  id: string;
  name: string;
  client: string;
  url: string;
  platform: string;
  type: string;
  /** Business-critical functions, e.g. ["Checkout", "Contact Form"] */
  businessFunctions: string[];
  createdAt: string;
  /** Optional WordPress REST API credentials for live scanning. */
  wpUsername?: string;
  wpAppPassword?: string;
};

/** PRIMARY — exactly what the user provides about a detected change. */
export type ChangeEvent = {
  id: string;
  websiteId: string;
  component: string;
  description: string;
  detectedAt: string;
  source: "Manual" | "CSV" | "Scan";
};

export type BusinessImpact = { label: string; level: string };
export type DependencyNode = { label: string; kind: "technical" | "business" };

/** DERIVED from a ChangeEvent + its Website. */
export type Issue = {
  id: string;
  changeId: string;
  websiteId: string;
  title: string;
  category: string;
  severity: Risk;
  businessImpact: string;
  status: IssueStatus;
  detected: string;
  detectedAt: string;
  component: string;
  description: string;
  impactCards: BusinessImpact[];
  dependencies: DependencyNode[];
  repair: {
    rootCause: string;
    proposedRepair: string;
    components: string[];
    expectedOutcome: string;
    validationRequired: string[];
    rollbackPlan: string;
  };
  safety: {
    score: number;
    riskLevel: Risk;
    decision: string;
    factors: { label: string; value: string }[];
  };
  patchPreview: {
    current: { label: string; value: string }[];
    proposed: { label: string; value: string }[];
    expectedEffect: string;
    journeyAffected: string;
    riskLevel: Risk;
    rollback: string;
    validationRequired: string;
  };
  journeyId?: string;
};

export type JourneyStep = { name: string };

/** DERIVED from a website's business functions. */
export type Journey = {
  id: string;
  name: string;
  websiteId: string;
  type: string;
  status: JourneyStatus;
  categories: string[];
  steps: JourneyStep[];
};

export type EvidenceScreenshot = { step: string; url: string };

/** DERIVED when an issue completes its assurance workflow. */
export type EvidenceRecord = {
  id: string;
  websiteId: string;
  issueId: string;
  issue: string;
  risk: Risk;
  outcome: string;
  date: string;
  createdAt: string;
  status: EvidenceStatus;
  businessImpact: string;
  dependencyChain: string;
  proposedRepair: string;
  safety: string;
  approval: string;
  patchPreview: string;
  repairStatus: string;
  validationPerformed: string;
  validationOutcome: string;
  rollback: string;
  before: { label: string; value: string }[];
  after: { label: string; value: string }[];
  timeline: { stage: string; time: string }[];
  screenshots?: EvidenceScreenshot[];
};

/** A website plus everything the UI derives from its related records. */
export type Website = WebsiteRecord & {
  status: WebsiteStatus;
  openIssues: number;
  protectedJourneys: number;
  lastChecked: string;
  baseline: {
    ssl: string;
    dns: string;
    components: string;
    thirdParty: string;
    businessFunctions: string;
    lastBaseline: string;
  };
  recentChanges: { change: string; when: string; risk: Risk; outcome: string }[];
};
