/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OverviewRouteImport } from './routes/overview'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as EvidenceIndexRouteImport } from './routes/evidence.index'
import { Route as EvidenceEvidenceIdRouteImport } from './routes/evidence.$evidenceId'
import { Route as IssuesIndexRouteImport } from './routes/issues.index'
import { Route as IssuesIssueIdRouteImport } from './routes/issues.$issueId'
import { Route as JourneysIndexRouteImport } from './routes/journeys.index'
import { Route as JourneysJourneyIdRouteImport } from './routes/journeys.$journeyId'
import { Route as WebsitesIndexRouteImport } from './routes/websites.index'
import { Route as WebsitesWebsiteIdRouteImport } from './routes/websites.$websiteId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OverviewRoute = OverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const EvidenceIndexRoute = EvidenceIndexRouteImport.update({
  id: '/evidence/',
  path: '/evidence/',
  getParentRoute: () => rootRouteImport,
} as any)
const EvidenceEvidenceIdRoute = EvidenceEvidenceIdRouteImport.update({
  id: '/evidence/$evidenceId',
  path: '/evidence/$evidenceId',
  getParentRoute: () => rootRouteImport,
} as any)
const IssuesIndexRoute = IssuesIndexRouteImport.update({
  id: '/issues/',
  path: '/issues/',
  getParentRoute: () => rootRouteImport,
} as any)
const IssuesIssueIdRoute = IssuesIssueIdRouteImport.update({
  id: '/issues/$issueId',
  path: '/issues/$issueId',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneysIndexRoute = JourneysIndexRouteImport.update({
  id: '/journeys/',
  path: '/journeys/',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneysJourneyIdRoute = JourneysJourneyIdRouteImport.update({
  id: '/journeys/$journeyId',
  path: '/journeys/$journeyId',
  getParentRoute: () => rootRouteImport,
} as any)
const WebsitesIndexRoute = WebsitesIndexRouteImport.update({
  id: '/websites/',
  path: '/websites/',
  getParentRoute: () => rootRouteImport,
} as any)
const WebsitesWebsiteIdRoute = WebsitesWebsiteIdRouteImport.update({
  id: '/websites/$websiteId',
  path: '/websites/$websiteId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/overview': typeof OverviewRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/evidence/$evidenceId': typeof EvidenceEvidenceIdRoute
  '/issues/$issueId': typeof IssuesIssueIdRoute
  '/journeys/$journeyId': typeof JourneysJourneyIdRoute
  '/websites/$websiteId': typeof WebsitesWebsiteIdRoute
  '/evidence/': typeof EvidenceIndexRoute
  '/issues/': typeof IssuesIndexRoute
  '/journeys/': typeof JourneysIndexRoute
  '/websites/': typeof WebsitesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/overview': typeof OverviewRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/evidence/$evidenceId': typeof EvidenceEvidenceIdRoute
  '/issues/$issueId': typeof IssuesIssueIdRoute
  '/journeys/$journeyId': typeof JourneysJourneyIdRoute
  '/websites/$websiteId': typeof WebsitesWebsiteIdRoute
  '/evidence': typeof EvidenceIndexRoute
  '/issues': typeof IssuesIndexRoute
  '/journeys': typeof JourneysIndexRoute
  '/websites': typeof WebsitesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/overview': typeof OverviewRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/evidence/$evidenceId': typeof EvidenceEvidenceIdRoute
  '/issues/$issueId': typeof IssuesIssueIdRoute
  '/journeys/$journeyId': typeof JourneysJourneyIdRoute
  '/websites/$websiteId': typeof WebsitesWebsiteIdRoute
  '/evidence/': typeof EvidenceIndexRoute
  '/issues/': typeof IssuesIndexRoute
  '/journeys/': typeof JourneysIndexRoute
  '/websites/': typeof WebsitesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/overview'
    | '/register'
    | '/settings'
    | '/evidence/$evidenceId'
    | '/issues/$issueId'
    | '/journeys/$journeyId'
    | '/websites/$websiteId'
    | '/evidence/'
    | '/issues/'
    | '/journeys/'
    | '/websites/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/overview'
    | '/register'
    | '/settings'
    | '/evidence/$evidenceId'
    | '/issues/$issueId'
    | '/journeys/$journeyId'
    | '/websites/$websiteId'
    | '/evidence'
    | '/issues'
    | '/journeys'
    | '/websites'
  id:
    | '__root__'
    | '/'
    | '/overview'
    | '/register'
    | '/settings'
    | '/evidence/$evidenceId'
    | '/issues/$issueId'
    | '/journeys/$journeyId'
    | '/websites/$websiteId'
    | '/evidence/'
    | '/issues/'
    | '/journeys/'
    | '/websites/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OverviewRoute: typeof OverviewRoute
  RegisterRoute: typeof RegisterRoute
  SettingsRoute: typeof SettingsRoute
  EvidenceEvidenceIdRoute: typeof EvidenceEvidenceIdRoute
  IssuesIssueIdRoute: typeof IssuesIssueIdRoute
  JourneysJourneyIdRoute: typeof JourneysJourneyIdRoute
  WebsitesWebsiteIdRoute: typeof WebsitesWebsiteIdRoute
  EvidenceIndexRoute: typeof EvidenceIndexRoute
  IssuesIndexRoute: typeof IssuesIndexRoute
  JourneysIndexRoute: typeof JourneysIndexRoute
  WebsitesIndexRoute: typeof WebsitesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overview': {
      id: '/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof OverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evidence/': {
      id: '/evidence/'
      path: '/evidence'
      fullPath: '/evidence/'
      preLoaderRoute: typeof EvidenceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evidence/$evidenceId': {
      id: '/evidence/$evidenceId'
      path: '/evidence/$evidenceId'
      fullPath: '/evidence/$evidenceId'
      preLoaderRoute: typeof EvidenceEvidenceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/issues/': {
      id: '/issues/'
      path: '/issues'
      fullPath: '/issues/'
      preLoaderRoute: typeof IssuesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/issues/$issueId': {
      id: '/issues/$issueId'
      path: '/issues/$issueId'
      fullPath: '/issues/$issueId'
      preLoaderRoute: typeof IssuesIssueIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journeys/': {
      id: '/journeys/'
      path: '/journeys'
      fullPath: '/journeys/'
      preLoaderRoute: typeof JourneysIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journeys/$journeyId': {
      id: '/journeys/$journeyId'
      path: '/journeys/$journeyId'
      fullPath: '/journeys/$journeyId'
      preLoaderRoute: typeof JourneysJourneyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/websites/': {
      id: '/websites/'
      path: '/websites'
      fullPath: '/websites/'
      preLoaderRoute: typeof WebsitesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/websites/$websiteId': {
      id: '/websites/$websiteId'
      path: '/websites/$websiteId'
      fullPath: '/websites/$websiteId'
      preLoaderRoute: typeof WebsitesWebsiteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OverviewRoute: OverviewRoute,
  RegisterRoute: RegisterRoute,
  SettingsRoute: SettingsRoute,
  EvidenceEvidenceIdRoute: EvidenceEvidenceIdRoute,
  IssuesIssueIdRoute: IssuesIssueIdRoute,
  JourneysJourneyIdRoute: JourneysJourneyIdRoute,
  WebsitesWebsiteIdRoute: WebsitesWebsiteIdRoute,
  EvidenceIndexRoute: EvidenceIndexRoute,
  IssuesIndexRoute: IssuesIndexRoute,
  JourneysIndexRoute: JourneysIndexRoute,
  WebsitesIndexRoute: WebsitesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
